<?php

namespace App\Admin\Controllers;

use Dcat\Admin\Http\Controllers\AuthController as BaseAuthController;
use Dcat\Admin\Layout\Content;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redis;

class AuthController extends BaseAuthController
{
    protected $view = 'admin.login';

    public function getLogin(Content $content)
    {
        return parent::getLogin($content); // TODO: Change the autogenerated stub
    }

    protected function sendLoginResponse(Request $request)
    {
        // 删除旧的会话信息
        $this->delSessionForRedis();
        $request->session()->regenerate();

        // 存储新的会话信息
        $this->setSessionForRedis();
        return $this->response()
            ->success('admin.login_successful')
            ->locationToIntended($this->getRedirectPath())
            ->send();
    }

    /**
     * 将会话 id 缓存入 redis
     */
    private function setSessionForRedis()
    {
        Redis::set('session_id_' . auth()->id(), '_database__cache:' . session()->getId());
    }

    /**
     * 清理旧会话
     */
    private function delSessionForRedis()
    {
        $key = Redis::get('session_id_' . auth()->id());

        if ($key) {
            $key = '_' . trim($key, "_database_");
            Redis::del($key);
        }
    }
}
